{% set name = "libpsl" %}
{% set version = "0.21.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rockdaboot/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1dcc9ceae8b128f3c0b3f654decd0e1e891afc6ff81098f227ef260449dae208

build:
  number: 0
  run_exports:
    # Just a guess
    - {{ pin_subpackage('libpsl', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - ninja
    - pkg-config
    - meson
  host:
    - icu

test:
  commands:
    - test -f ${PREFIX}/include/libpsl.h                       # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libpsl.pc                # [unix]
    - test -f ${PREFIX}/lib/libpsl.dylib                       # [osx]
    - test -f ${PREFIX}/lib/libpsl.so                          # [linux]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\libpsl.pc exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\psl.lib exit 1               # [win]
    - if not exist %LIBRARY_INC%\\libpsl.h exit 1              # [win]
    - if not exist %LIBRARY_BIN%\\psl-5.dll exit 1             # [win]

about:
  home: https://github.com/rockdaboot/libpsl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A C library to handle the Public Suffix List

extra:
  recipe-maintainers:
    - tschoonj
